"""empty message

Revision ID: 02301ba0897d
Revises: 7b341695f43f
Create Date: 2022-10-22 23:20:38.986299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02301ba0897d'
down_revision = '7b341695f43f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_donation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=1200), nullable=False),
    sa.Column('presentation', sa.String(length=120), nullable=False),
    sa.Column('active_component', sa.String(length=120), nullable=False),
    sa.Column('expiration_date', sa.String(length=120), nullable=False),
    sa.Column('specification', sa.String(length=120), nullable=False),
    sa.Column('quantity', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('medicine_picture', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('city', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('hashed_password', sa.String(length=500), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('name', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('profile_picture', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('salt', sa.String(length=500), nullable=False))
    op.create_unique_constraint(None, 'user', ['salt'])
    op.create_unique_constraint(None, 'user', ['hashed_password'])
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'salt')
    op.drop_column('user', 'profile_picture')
    op.drop_column('user', 'name')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'hashed_password')
    op.drop_column('user', 'city')
    op.drop_table('post_donation')
    # ### end Alembic commands ###
