"""empty message

Revision ID: 09f6dfb64d40
Revises: 02301ba0897d
Create Date: 2022-10-24 23:52:41.375928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09f6dfb64d40'
down_revision = '02301ba0897d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_donation', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'post_donation', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_donation', type_='foreignkey')
    op.drop_column('post_donation', 'user_id')
    # ### end Alembic commands ###
