"""empty message

Revision ID: 4ad8e9a3aa2e
Revises: 86d461d954cd
Create Date: 2022-10-31 22:14:48.288381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ad8e9a3aa2e'
down_revision = '86d461d954cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_medicine_picture_key', 'post', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('post_medicine_picture_key', 'post', ['medicine_picture'])
    # ### end Alembic commands ###
