"""empty message

Revision ID: 7479cb6efcda
Revises: a1120844a470
Create Date: 2022-10-26 21:54:45.722341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7479cb6efcda'
down_revision = 'a1120844a470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_donation', 'user_last_name')
    op.drop_column('post_donation', 'user_city')
    op.drop_column('post_donation', 'user_name')
    op.drop_column('post_donation', 'user_profile_picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_donation', sa.Column('user_profile_picture', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('post_donation', sa.Column('user_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('post_donation', sa.Column('user_city', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('post_donation', sa.Column('user_last_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
