"""empty message

Revision ID: a1120844a470
Revises: 09f6dfb64d40
Create Date: 2022-10-25 22:44:22.221881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1120844a470'
down_revision = '09f6dfb64d40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_donation', sa.Column('user_name', sa.String(length=120), nullable=False))
    op.add_column('post_donation', sa.Column('user_last_name', sa.String(length=120), nullable=False))
    op.add_column('post_donation', sa.Column('user_city', sa.String(length=120), nullable=False))
    op.add_column('post_donation', sa.Column('user_profile_picture', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_donation', 'user_profile_picture')
    op.drop_column('post_donation', 'user_city')
    op.drop_column('post_donation', 'user_last_name')
    op.drop_column('post_donation', 'user_name')
    # ### end Alembic commands ###
