"""empty message

Revision ID: f2eaf0d83182
Revises: 
Create Date: 2022-11-09 04:12:36.913781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2eaf0d83182'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=400), nullable=False),
    sa.Column('name', sa.String(length=400), nullable=False),
    sa.Column('last_name', sa.String(length=400), nullable=False),
    sa.Column('city', sa.String(length=400), nullable=False),
    sa.Column('hashed_password', sa.String(length=400), nullable=False),
    sa.Column('salt', sa.String(length=400), nullable=False),
    sa.Column('phone', sa.String(length=400), nullable=True),
    sa.Column('profile_picture', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('hashed_password'),
    sa.UniqueConstraint('salt')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=1200), nullable=True),
    sa.Column('presentation', sa.String(length=120), nullable=True),
    sa.Column('active_component', sa.String(length=120), nullable=True),
    sa.Column('expiration_date', sa.String(length=120), nullable=True),
    sa.Column('dosis', sa.String(length=120), nullable=True),
    sa.Column('quantity', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('medicine_picture', sa.String(length=500), nullable=True),
    sa.Column('typeof', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trading_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=1200), nullable=True),
    sa.Column('presentation', sa.String(length=120), nullable=True),
    sa.Column('active_component', sa.String(length=120), nullable=True),
    sa.Column('expiration_date', sa.String(length=120), nullable=True),
    sa.Column('dosis', sa.String(length=120), nullable=True),
    sa.Column('quantity', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('medicine_picture', sa.String(length=120), nullable=True),
    sa.Column('req_presentation', sa.String(length=120), nullable=True),
    sa.Column('req_active_component', sa.String(length=120), nullable=True),
    sa.Column('req_expiration_date', sa.String(length=120), nullable=True),
    sa.Column('req_dosis', sa.String(length=120), nullable=True),
    sa.Column('req_quantity', sa.String(length=120), nullable=True),
    sa.Column('req_name', sa.String(length=120), nullable=True),
    sa.Column('req_medicine_picture', sa.String(length=120), nullable=True),
    sa.Column('typeof', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medicine_picture'),
    sa.UniqueConstraint('req_medicine_picture')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trading_post')
    op.drop_table('post')
    op.drop_table('user')
    # ### end Alembic commands ###
